name: Publish Poetry package

on:
  push:
    branches:
      - master

jobs:
  publish-to-pypi:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
